### ISSUE TITLE
Do you mean you will have two view files according to the README??

### ISSUE THREAD

**Issue by TJRoger** [maxmirazh33/yii2-uploadable-cropable-image#8]

**Comment by maxmirazh33** [comment]
@TJRoger, I didn't understand you. Can you give more info about your question?

**Comment by TJRoger** [comment]
in your view file:

echo $form->field($model, 'avatar')->widget('maxmirazh33\image\Widget');
After, in your view:

echo Html::img($model->getImageUrl('avatar'));
echo Html::img($model->getImageUrl('logo', 'mini')); //get url of thumbnail named 'mini' for 'logo' attribute

**Comment by maxmirazh33** [comment]
@TJRoger, first view - image input, view with form(in backend e.g.), second view - image output(in frontend e.g.).

**Comment by TJRoger** [comment]
@maxmirazh33 thanks!
